import React, { createContext, useContext, useState } from "react";

export type Language = "pt" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  pt: {
    // Sidebar
    "sidebar.home": "Início",
    "sidebar.inbox": "Inbox",
    "sidebar.gallery": "Galeria",
    "sidebar.deviations": "Desvios",
    "sidebar.calendar": "Calendário",
    "sidebar.ideas": "Ideias",
    "sidebar.settings": "Configurações",
    "sidebar.logout": "Sair",
    "sidebar.profile": "Perfil",
    "sidebar.backToDashboard": "Voltar ao Dashboard",
    "sidebar.collapse": "Recolher",
    "sidebar.expand": "Expandir",

    // Profile
    "profile.title": "Conta",
    "profile.picture": "Foto de Perfil",
    "profile.uploadImage": "Enviar Imagem",
    "profile.removeImage": "Remover",
    "profile.imageSupportInfo": "Suportamos PNGs, JPEGs e GIFs menores de 10MB",
    "profile.firstName": "Primeiro Nome",
    "profile.lastName": "Sobrenome",
    "profile.email": "E-mail",
    "profile.editEmail": "Editar E-mail",
    "profile.emailInfo": "Usado para fazer login na sua conta",
    "profile.password": "Senha",
    "profile.passwordInfo": "Faça login com sua senha em vez de usar códigos temporários",
    "profile.newPassword": "Nova Senha (opcional)",
    "profile.neuroTitle": "Neurodivergência (Opcional)",
    "profile.isNeuro": "Sou neurodivergente",
    "profile.neuroSelectAll": "Selecione todas que se aplicam a você:",
    "profile.otherNeuro": "Outro (separado por vírgula)",
    "profile.cancel": "Cancelar",
    "profile.save": "Salvar",
    "profile.saving": "Salvando...",
    "profile.successAvatar": "Foto de perfil atualizada com sucesso!",
    "profile.errorAvatarSize": "A imagem deve ter menos de 10MB.",
    "profile.errorAvatarUpload": "Erro ao atualizar foto: ",
    "profile.successSave": "Perfil salvo com sucesso!",
    "profile.errorSave": "Erro ao salvar: ",

    // Help Mode
    "help.title": "Guia do Broto",
    "help.welcome": "Bem-vindo ao Broto, seu santuário de produtividade. Aqui estão algumas dicas de como usar o app.",
    "help.blocksTitle": "Blocos & Galeria",
    "help.blocksDesc": "Os Blocos são como cadernos ou áreas de foco. Você pode criar blocos para Projetos, Estudos, ou Vida Pessoal. A Galeria é onde você os organiza.",
    "help.tasksTitle": "Tarefas & Modo Foco",
    "help.tasksDesc": "Dentro de cada bloco, você cria tarefas. Para as mais importantes, use o botão 'Focar' para iniciar uma sessão imersiva e trabalhar sem distrações.",
    "help.triageTitle": "Triagem & Desvios",
    "help.triageDesc": "Quando estiver focado e pensar em outra coisa, clique em 'Capturar Desvio'. Esse pensamento vai para a Triagem, para você organizar depois sem perder o fluxo.",
    "help.ideasTitle": "Ideias Futuras",
    "help.ideasDesc": "Ideias criativas sem pressão de prazo podem ser guardadas no mural de Ideias Futuras.",
    "help.calendarTitle": "Calendário",
    "help.calendarDesc": "Prazos importantes e sessões agendadas ficam todos organizados no seu Calendário, ajudando no planejamento.",
    "help.close": "Entendi!",
    "help.tooltipMsg": "Primeiro acesso? Clique aqui para aprender a usar o app!",

    // AuthPage
    "auth.title": "Broto",
    "auth.subtitle": "Santuário para sua mente",
    "auth.email": "E-mail",
    "auth.password": "Senha",
    "auth.login": "Entrar",
    "auth.signup": "Cadastrar",
    "auth.or": "Ou continue com",
    "auth.noAccount": "Não tem uma conta? Cadastrar-se",
    "auth.hasAccount": "Já tem uma conta? Entre",
    "auth.invalidEmail": "E-mail inválido",
    "auth.passwordMin": "A senha deve ter pelo menos 6 caracteres",
    "auth.confirmEmailTitle": "Confirme seu E-mail",
    "auth.backToLogin": "Voltar para o Login",

    // DashboardPage
    "dashboard.title": "Hoje",
    "dashboard.activeTask": "Tarefa Ativa",
    "dashboard.noActiveTask": "Nenhuma tarefa ativa",
    "dashboard.chooseTask": "Escolha uma tarefa para começar.",
    "dashboard.noTasksToday": "Nenhuma tarefa planejada para hoje.",
    "dashboard.appointments": "Compromissos",
    "dashboard.noAppointments": "Nenhum evento agendado.",
    "dashboard.activeBlocks": "Blocos Ativos",
    "dashboard.noActiveBlocks": "Nenhum bloco criado ainda.",
    "dashboard.tasks": "tarefas",
    "dashboard.completed": "concluídas",
    "dashboard.dayPlan": "Plano do Dia",
    "dashboard.selectBlocks": "Selecionar Blocos",
    "dashboard.noDayPlan": "Nenhum bloco selecionado para hoje.",
    "dashboard.dayPlanDesc": "Escolha os blocos que vai trabalhar hoje.",
    "dashboard.addBlocks": "Adicionar Blocos",
    "dashboard.selectBlocksTitle": "Selecionar Blocos do Dia",
    "dashboard.classifyBlocks": "Classificar Blocos",
    "dashboard.noPriority": "Sem prioridade",
    "dashboard.confirm": "Confirmar",
    "dashboard.removeFromDay": "Remover do dia",
    "dashboard.classifyStep": "Classifique a prioridade dos blocos selecionados:",
    "dashboard.selectStep": "Selecione os blocos para trabalhar hoje:",
    "dashboard.back": "Voltar",
    "dashboard.next": "Avançar",

    // GaleriaPage
    "gallery.title": "Galeria de Blocos",
    "gallery.subtitle": "Suas áreas de foco atuais, organizadas.",
    "gallery.newBlock": "Novo Bloco",
    "gallery.noBlocks": "Nenhum bloco criado. Clique em 'Novo Bloco' para começar!",
    "gallery.completed": "concluída",
    "gallery.archiveConfirmMessage": "Tem certeza que quer arquivar este bloco? Você pode restaurá-lo depois.",
    "gallery.deleteConfirmMessage": "Tem certeza que quer deletar \"{blocName}\" permanentemente? Esta ação não pode ser desfeita.",

    // ArquivosBlocoPage
    "archive.title": "Blocos Arquivados",
    "archive.subtitle": "Gerencie seus blocos arquivados",
    "archive.empty": "Nenhum bloco arquivado.",
    "archive.emptyDesc": "Os blocos que você arquivar aparecerão aqui.",
    "archive.restore": "Restaurar",
    "archive.deletePermanent": "Excluir",
    "archive.deleteTitle": "Excluir permanentemente",
    "archive.deleteMessage": "Tem certeza que quer excluir \"{blocName}\" permanentemente? Esta ação não pode ser desfeita.",
    "archive.backToGallery": "Voltar",

    // BlocoDetailPage
    "block.backToGallery": "← Voltar para galeria",
    "block.inProgress": "Em Andamento",
    "block.pending": "Pendentes",
    "block.completed": "Concluídas",
    "block.noTasks": "Nenhuma tarefa neste bloco ainda.",
    "block.noTasksTitle": "Nenhuma tarefa ainda",
    "block.notFound": "Bloco não encontrado",
    "block.newTask": "Nova Tarefa",
    "block.deleteConfirm": "Tem certeza que quer deletar esta tarefa?",
    "block.deleteBlockConfirm": "Tem certeza que deseja deletar este bloco? Isso apagará todas as tarefas associadas!",

    // DesviosPage
    "deviations.title": "Quadro de Desvios",
    "deviations.subtitle": "Ideias e pensamentos capturados fora de hora para processamento posterior.",
    "deviations.all": "Todos",
    "deviations.noDeviations": "Nenhum desvio ainda",
    "deviations.emptyMessage": "Use a opção \"Capturar Desvio\" durante o Focus Mode para registrar pensamentos fora do foco.",
    "deviations.noFiltered": "Nenhum desvio com esses filtros.",
    "deviations.origin": "De:",

    // CalendarioPage
    "calendar.title": "Calendário",
    "calendar.subtitle": "Visualize seus eventos e datas importantes.",
    "calendar.workBlocks": "Blocos de Trabalho",
    "calendar.personalSanctuary": "Santuário Pessoal",
    "calendar.futureIdeas": "Ideias Futuras",
    "calendar.newEvent": "Novo Evento",
    "calendar.editEvent": "Editar Evento",
    "calendar.eventTitle": "Título do Evento *",
    "calendar.eventTime": "Horário (opcional)",
    "calendar.eventDate": "Data",
    "calendar.eventColor": "Cor",
    "calendar.customColor": "Cor Personalizada",
    "calendar.addPreset": "+ Nova Classificação",
    "calendar.editPreset": "Editar Classificação",
    "calendar.deleteEventConfirm": "Deseja remover este evento?",
    "calendar.deletePresetConfirm": "Deseja remover esta classificação?",
    "calendar.presetLabelPlaceholder": "Nome da classificação",
    "calendar.presetExams": "Provas",
    "calendar.presetJobs": "Trabalhos",
    "calendar.presetStudies": "Estudos",
    "calendar.presetLeisure": "Lazer",
    "calendar.presetPersonal": "Pessoal",
    "calendar.prev": "← Anterior",
    "calendar.today": "Hoje",
    "calendar.next": "Próximo →",
    "calendar.eventTypes": "Tipos de Evento",
    "calendar.more": "mais",
    "calendar.january": "Janeiro",
    "calendar.february": "Fevereiro",
    "calendar.march": "Março",
    "calendar.april": "Abril",
    "calendar.may": "Maio",
    "calendar.june": "Junho",
    "calendar.july": "Julho",
    "calendar.august": "Agosto",
    "calendar.september": "Setembro",
    "calendar.october": "Outubro",
    "calendar.november": "Novembro",
    "calendar.december": "Dezembro",
    "calendar.sun": "Dom",
    "calendar.mon": "Seg",
    "calendar.tue": "Ter",
    "calendar.wed": "Qua",
    "calendar.thu": "Qui",
    "calendar.fri": "Sex",
    "calendar.sat": "Sáb",

    // IdeiasPage
    "ideas.title": "Ideias Futuras",
    "ideas.subtitle": "Um espaço sem pressão para inspirações e possibilidades.",
    "ideas.newIdea": "Nova Ideia",
    "ideas.noIdeas": "Nenhuma ideia ainda",
    "ideas.noIdeasDesc": "Comece a adicionar ideias futuras quando a inspiração bater.",
    "ideas.deleteConfirm": "Deseja remover esta ideia?",

    // TriagemPage (Inbox)
    "inbox.title": "Triagem de Pensamentos",
    "inbox.subtitle": "",
    "inbox.noThoughts": "Nenhuma captura pendente",
    "inbox.thoughtsDesc": "Seus pensamentos capturados aparecerão aqui.",
    "inbox.triageAsTask": "Criar Tarefa",
    "inbox.triageAsIdea": "Ideia Futura",
    "inbox.triageAsNote": "Adicionar Nota",
    "inbox.discard": "Descartar",
    "inbox.selectBlock": "Selecione o bloco para esta tarefa:",
    "inbox.cancel": "Cancelar",
    "inbox.create": "Criar",
    "inbox.creating": "Criando...",
    "inbox.triageAsIdeaSuccess": "Convertido para ideia futura!",
    "inbox.triageAsNoteSuccess": "Convertido para anotação!",
    "inbox.loading": "Carregando inbox...",

    // ConfiguracoesPage
    "settings.title": "Configurações",
    "settings.subtitle": "Ajuste o santuário para as suas necessidades",
    "settings.error": "Erro ao carregar configurações",
    "settings.language": "Idioma / Language",
    "settings.languageDesc": "Escolha o idioma de exibição do app",
    "settings.focoRitmo": "Foco & Ritmo",
    "settings.focoRitmoDesc": "Ajuste como o app entende seu ritmo de trabalho",
    "settings.limiarHiperfoco": "Limiar de Hiperfoco:",
    "settings.limiarDesc": "Quanto tempo a mais do estimado para o app avisar que você está em hiperfoco?",
    "settings.limiarValues": "100% = exatamente no tempo | 150% = 50% a mais | 300% = 3x o tempo",
    "settings.horarioFimDia": "Hora de \"fim do dia\"",
    "settings.horarioFimDiaDesc": "Quando o app para de contar tempo gasto (útil para separar dia de trabalho)",
    "settings.ia": "Assistência Inteligente",
    "settings.iaDesc": "Recursos que usam IA para ajudar",
    "settings.iaCheckbox": "Ativar sugestões de tempo estimado via IA",
    "settings.iaCheckboxDesc": "O app pode sugerir quanto tempo uma tarefa deve levar",
    "settings.camposAvancados": "Campos de Tarefa Avançados",
    "settings.camposAvancadosDesc": "Quais campos adicionais aparecer ao criar uma tarefa?",
    "settings.energiaEstimada": "Energia Estimada (baixa/média/alta)",
    "settings.contexto": "Contexto (ex: \"preciso do café da manhã\", \"rápido entre reuniões\")",
    "settings.prioridade": "Prioridade Numérica (1-5)",
    "settings.camposDesc": "Campos desativados não aparecem ao criar tarefas, mantendo a interface simples",
    "settings.modulosOpcionais": "Módulos Opcionais",
    "settings.modulosOpcionaisDesc": "Funcionalidades que você pode ativar ou desativar",
    "settings.diarioVisual": "Diário Visual (planejado para Fase 11)",
    "settings.rastreadorHabitos": "Rastreador de Hábitos (planejado para Fase 11)",
    "settings.autoSave": "Todas as mudanças são salvas automaticamente.",
    "settings.saving": "Salvando...",
    "settings.pomodoro": "Técnica de Pomodoro",
    "settings.pomodoroDesc": "Personalize seus intervalos de trabalho e descanso",
    "settings.pomoDuration": "Duração de cada sessão de trabalho",
    "settings.pomoDurationDesc": "Quanto tempo você trabalha em cada \"tomate\" (sessão focada)",
    "settings.pomoShortBreak": "Pausa curta entre sessões",
    "settings.pomoShortBreakDesc": "Tempo de descanso rápido após cada sessão de trabalho",
    "settings.pomoLongBreak": "Pausa longa de recarga",
    "settings.pomoLongBreakDesc": "Descanso maior para se recuperar depois de várias sessões",
    "settings.pomoUntilLongBreak": "Sessões até a pausa longa",
    "settings.pomoUntilLongBreakDesc": "Quantas sessões completar antes de fazer uma pausa longa",
    "task.pomodoroEstimated": "Pomodoros que precisa",

    // Componentes: TaskCard & TaskModal
    "task.programming": "Programação",
    "task.currentFocus": "Foco Atual",
    "task.isProgramming": "É uma tarefa de programação?",
    "task.tip": "Dica: Após salvar, clique em \"▼ Ver checklist\" para adicionar itens de checklist.",
    "task.edit": "Editar Tarefa",
    "task.create": "Criar Nova Tarefa",
    "task.title": "Título *",
    "task.description": "Descrição",
    "task.estimatedTime": "Tempo estimado (minutos)",
    "task.confirmPassword": "Confirmar Senha",
    "task.save": "Salvar",
    "task.saving": "Salvando...",
    "task.checklist": "Checklist",
    "task.addChecklist": "+ Adicionar item",
    "task.newChecklistItem": "Novo item...",
    "task.verChecklist": "Ver checklist",
    "task.ocultarChecklist": "Ocultar checklist",
    "task.titleRequired": "Título da tarefa é obrigatório",

    // Componentes: CaptureDesvioModal
    "deviation.captured": "Desvio Capturado",
    "deviation.subtitle": "Registre este pensamento fora do escopo e volte ao foco.",
    "deviation.placeholder": "No que você está pensando agora?",
    "deviation.placeholderText": "Ex: Lembrei de responder email do cliente...",
    "deviation.errorEmpty": "Descreva o pensamento",
    "deviation.errorCapture": "Erro ao capturar desvio",
    "deviation.tag": "Como categorizar este pensamento?",
    "deviation.tagNone": "Sem Categoria",
    "deviation.tagUrgent": "Urgente",
    "deviation.tagIdea": "Ideia Espontânea",
    "deviation.tagUnrelated": "Fora do Escopo",
    "deviation.save": "Salvar e Continuar Focado",
    "deviation.saving": "Salvando...",
    "deviation.back": "Voltar",

    // Componentes: CaptureThoughtModal
    "thought.capture": "Capturar Pensamento",
    "thought.placeholder": "Escreva o que passou pela sua cabeça...",
    "thought.details": "Mais Detalhes (Opcional)",
    "thought.detailsPlaceholder": "Adicione contexto ou notas extras...",
    "thought.category": "Categoria Inicial",
    "thought.catIdea": "Ideia",
    "thought.catTask": "Tarefa",
    "thought.catNote": "Nota",
    "thought.save": "Enviar para a Inbox",
    "thought.saving": "Enviando...",

    // Componentes: BlocoModal
    "block.createTitle": "Criar Novo Bloco",
    "block.editTitle": "Editar Bloco",
    "block.icon": "Ícone",
    "block.name": "Nome do Bloco *",
    "block.namePlaceholder": "Ex: Estudos Universitários",
    "block.desc": "Descrição",
    "block.descPlaceholder": "Descrição breve...",
    "block.category": "Categoria",
    "block.catLearning": "Aprendizado",
    "block.catCareer": "Carreira",
    "block.catPersonal": "Pessoal",
    "block.catLeisure": "Lazer",
    "block.metaLabel": "Nome da Meta",
    "block.metaLabelPlaceholder": "Ex: Capítulos",
    "block.metaTotal": "Meta Total",
    "block.save": "Salvar",
    "block.saving": "Salvando...",
    "block.addLink": "Adicionar Link",
    "block.linkTitlePlaceholder": "Título do link",
    "block.linkUrlPlaceholder": "https://...",
    "block.linkFieldsRequired": "Preencha o título e o link",
    "block.linkSaveError": "Erro ao salvar link",

    // Componentes: IdeiaModal
    "idea.createTitle": "Criar Nova Ideia",
    "idea.editTitle": "Editar Ideia",
    "idea.titleLabel": "Título *",
    "idea.titlePlaceholder": "Ideia brilhante...",
    "idea.desc": "Descrição",
    "idea.descPlaceholder": "Mais detalhes...",
    "idea.tag": "Tag",
    "idea.save": "Salvar",
    "idea.saving": "Salvando...",

    // FocusMode
    "focus.active": "Foco Ativo",
    "focus.completed": "Concluir",
    "focus.capture": "Capturar Desvio",
    "focus.confirmExit": "Tem certeza que deseja sair do Focus Mode? O tempo gasto atual será perdido.",
    "focus.exitWithoutSaving": "Sair (sem salvar)",
    "focus.estimated": "Estimado",
    "focus.elapsed": "Decorrido",
    "focus.pause": "⏸️ Pausar",
    "focus.resume": "▶️ Retomar",
    "focus.hyperfocusWarning": "⚡ Você ultrapassou o limite de hiperfoco! Está tudo bem?",

    // Mensagens de Erro
    "error.savingBloco": "Erro ao salvar bloco",
    "error.savingTask": "Erro ao salvar tarefa",

    // Componentes Genéricos (BlocoCard, TaskCard, etc)
    "common.user": "Usuário",
    "common.active": "Ativo",
    "common.edit": "Editar",
    "common.archive": "Arquivar",
    "common.confirm": "Confirmar",
    "common.cancel": "Cancelar",
    "common.delete": "Deletar",
    "common.save": "Salvar",
    "common.close": "Fechar",
    "common.restore": "Restaurar",
    "common.unmark": "Desmarcar",
    "common.markComplete": "Marcar concluído",
    "common.focusMode": "Modo Foco",
    "common.default": "Padrão",
    "common.custom": "Cor Personalizada",
    "common.done": "Pronto",

    // ColorWheelPicker
    "color.default": "Padrão",
    "color.custom": "Cor Personalizada",
    "color.hexCode": "Código HEX",
    "color.done": "Pronto",

    "dates.title": "Datas Importantes",
    "dates.add": "Adicionar Data",
    "dates.noDates": "Nenhuma data importante definida para este bloco.",
    "dates.titleLabel": "Título",
    "dates.descLabel": "Descrição (opcional)",
    "dates.dateLabel": "Data",
    "notifications.title": "Notificações",
    "notifications.empty": "Nenhuma notificação nova.",
    "notifications.markRead": "Marcar como lida",
  },
  en: {
    // Sidebar
    "sidebar.home": "Home",
    "sidebar.inbox": "Inbox",
    "sidebar.gallery": "Gallery",
    "sidebar.deviations": "Deviations",
    "sidebar.calendar": "Calendar",
    "sidebar.ideas": "Ideas",
    "sidebar.settings": "Settings",
    "sidebar.logout": "Logout",
    "sidebar.profile": "Profile",
    "sidebar.backToDashboard": "Back to Dashboard",
    "sidebar.collapse": "Collapse",
    "sidebar.expand": "Expand",

    // Profile
    "profile.title": "Account",
    "profile.picture": "Profile Picture",
    "profile.uploadImage": "Upload Image",
    "profile.removeImage": "Remove",
    "profile.imageSupportInfo": "We support PNGs, JPEGs and GIFs under 10MB",
    "profile.firstName": "First Name",
    "profile.lastName": "Last Name",
    "profile.email": "Email",
    "profile.editEmail": "Edit Email",
    "profile.emailInfo": "Used to log in to your account",
    "profile.password": "Password",
    "profile.passwordInfo": "Log in with your password instead of using temporary login codes",
    "profile.newPassword": "New Password (optional)",
    "profile.neuroTitle": "Neurodivergence (Optional)",
    "profile.isNeuro": "I am neurodivergent",
    "profile.neuroSelectAll": "Select all that apply to you:",
    "profile.otherNeuro": "Other (comma separated)",
    "profile.cancel": "Cancel",
    "profile.save": "Save",
    "profile.saving": "Saving...",
    "profile.successAvatar": "Profile picture updated successfully!",
    "profile.errorAvatarSize": "Image must be under 10MB.",
    "profile.errorAvatarUpload": "Error updating picture: ",
    "profile.successSave": "Profile saved successfully!",
    "profile.errorSave": "Error saving: ",

    // Help Mode
    "help.title": "Broto Guide",
    "help.welcome": "Welcome to Broto, your productivity sanctuary. Here are some tips on how to use the app.",
    "help.blocksTitle": "Blocks & Gallery",
    "help.blocksDesc": "Blocks are like notebooks or focus areas. You can create blocks for Projects, Studies, or Personal Life. The Gallery is where you organize them.",
    "help.tasksTitle": "Tasks & Focus Mode",
    "help.tasksDesc": "Inside each block, you create tasks. For the most important ones, use the 'Focus Mode' button to start an immersive session and work without distractions.",
    "help.triageTitle": "Triage & Deviations",
    "help.triageDesc": "When focused and you think of something else, click 'Capture Deviation'. This thought goes to Triage, so you can deal with it later without losing your flow.",
    "help.ideasTitle": "Future Ideas",
    "help.ideasDesc": "Creative ideas without deadline pressure can be saved on the Future Ideas board.",
    "help.calendarTitle": "Calendar",
    "help.calendarDesc": "Important deadlines and scheduled sessions are all organized in your Calendar, helping you plan your day.",
    "help.close": "Got it!",
    "help.tooltipMsg": "First time here? Click here to learn how to use the app!",

    // AuthPage
    "auth.title": "Broto",
    "auth.subtitle": "Sanctuary for your mind",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.login": "Login",
    "auth.signup": "Sign Up",
    "auth.or": "Or continue with",
    "auth.noAccount": "Don't have an account? Sign Up",
    "auth.hasAccount": "Already have an account? Login",
    "auth.invalidEmail": "Invalid email",
    "auth.passwordMin": "Password must be at least 6 characters",
    "auth.confirmEmailTitle": "Confirm your Email",
    "auth.backToLogin": "Back to Login",

    // DashboardPage
    "dashboard.title": "Today",
    "dashboard.activeTask": "Active Task",
    "dashboard.noActiveTask": "No active task",
    "dashboard.chooseTask": "Choose a task to start.",
    "dashboard.noTasksToday": "No tasks planned for today.",
    "dashboard.appointments": "Appointments",
    "dashboard.noAppointments": "No scheduled events.",
    "dashboard.activeBlocks": "Active Blocks",
    "dashboard.noActiveBlocks": "No blocks created yet.",
    "dashboard.tasks": "tasks",
    "dashboard.completed": "completed",
    "dashboard.dayPlan": "Day Plan",
    "dashboard.selectBlocks": "Select Blocks",
    "dashboard.noDayPlan": "No blocks selected for today.",
    "dashboard.dayPlanDesc": "Choose blocks to work on today.",
    "dashboard.addBlocks": "Add Blocks",
    "dashboard.selectBlocksTitle": "Select Today's Blocks",
    "dashboard.classifyBlocks": "Classify Blocks",
    "dashboard.noPriority": "No priority",
    "dashboard.confirm": "Confirm",
    "dashboard.removeFromDay": "Remove from day",
    "dashboard.classifyStep": "Classify the priority of selected blocks:",
    "dashboard.selectStep": "Select blocks to work on today:",
    "dashboard.back": "Back",
    "dashboard.next": "Next",

    // GaleriaPage
    "gallery.title": "Block Gallery",
    "gallery.subtitle": "Your current focal areas, neatly organized.",
    "gallery.newBlock": "New Block",
    "gallery.noBlocks": "No blocks created. Click 'New Block' to start!",
    "gallery.completed": "completed",
    "gallery.archiveConfirmMessage": "Are you sure you want to archive this block? You can restore it later.",
    "gallery.deleteConfirmMessage": "Are you sure you want to permanently delete \"{blocName}\"? This action cannot be undone.",

    // ArquivosBlocoPage
    "archive.title": "Archived Blocks",
    "archive.subtitle": "Manage your archived blocks",
    "archive.empty": "No archived blocks.",
    "archive.emptyDesc": "Blocks you archive will appear here.",
    "archive.restore": "Restore",
    "archive.deletePermanent": "Delete",
    "archive.deleteTitle": "Delete Permanently",
    "archive.deleteMessage": "Are you sure you want to permanently delete \"{blocName}\"? This action cannot be undone.",
    "archive.backToGallery": "Back",

    // BlocoDetailPage
    "block.backToGallery": "← Back to gallery",
    "block.inProgress": "In Progress",
    "block.pending": "Pending",
    "block.completed": "Completed",
    "block.noTasks": "No tasks in this block yet.",
    "block.noTasksTitle": "No tasks yet",
    "block.notFound": "Block not found",
    "block.newTask": "New Task",
    "block.deleteConfirm": "Are you sure you want to delete this task?",
    "block.deleteBlockConfirm": "Are you sure you want to delete this block? This will delete all associated tasks!",

    // DesviosPage
    "deviations.title": "Deviation Board",
    "deviations.subtitle": "Off-schedule ideas and thoughts captured for later processing.",
    "deviations.all": "All",
    "deviations.noDeviations": "No deviations yet",
    "deviations.emptyMessage": "Use the \"Capture Deviation\" option during Focus Mode to record off-focus thoughts.",
    "deviations.noFiltered": "No deviations with these filters.",
    "deviations.origin": "From:",

    // CalendarioPage
    "calendar.title": "Calendar",
    "calendar.subtitle": "Visualize your events and important dates.",
    "calendar.workBlocks": "Work Blocks",
    "calendar.personalSanctuary": "Personal Sanctuary",
    "calendar.futureIdeas": "Future Ideas",
    "calendar.newEvent": "New Event",
    "calendar.editEvent": "Edit Event",
    "calendar.eventTitle": "Event Title *",
    "calendar.eventTime": "Time (optional)",
    "calendar.eventDate": "Date",
    "calendar.eventColor": "Color",
    "calendar.customColor": "Custom Color",
    "calendar.addPreset": "+ New Classification",
    "calendar.editPreset": "Edit Classification",
    "calendar.deleteEventConfirm": "Are you sure you want to delete this event?",
    "calendar.deletePresetConfirm": "Are you sure you want to delete this classification?",
    "calendar.presetLabelPlaceholder": "Classification name",
    "calendar.presetExams": "Exams",
    "calendar.presetJobs": "Work",
    "calendar.presetStudies": "Studies",
    "calendar.presetLeisure": "Leisure",
    "calendar.presetPersonal": "Personal",
    "calendar.prev": "← Previous",
    "calendar.today": "Today",
    "calendar.next": "Next →",
    "calendar.eventTypes": "Event Types",
    "calendar.more": "more",
    "calendar.january": "January",
    "calendar.february": "February",
    "calendar.march": "March",
    "calendar.april": "April",
    "calendar.may": "May",
    "calendar.june": "June",
    "calendar.july": "July",
    "calendar.august": "August",
    "calendar.september": "September",
    "calendar.october": "October",
    "calendar.november": "November",
    "calendar.december": "December",
    "calendar.sun": "Sun",
    "calendar.mon": "Mon",
    "calendar.tue": "Tue",
    "calendar.wed": "Wed",
    "calendar.thu": "Thu",
    "calendar.fri": "Fri",
    "calendar.sat": "Sat",

    // IdeiasPage
    "ideas.title": "Future Ideas",
    "ideas.subtitle": "A pressure-free space for inspirations and possibilities.",
    "ideas.newIdea": "New Idea",
    "ideas.noIdeas": "No ideas yet",
    "ideas.noIdeasDesc": "Start adding future ideas when inspiration strikes.",
    "ideas.deleteConfirm": "Do you want to remove this idea?",

    // TriagemPage (Inbox)
    "inbox.title": "Thought Triage",
    "inbox.subtitle": "",
    "inbox.noThoughts": "No pending captures",
    "inbox.thoughtsDesc": "Your captured thoughts will appear here.",
    "inbox.triageAsTask": "Create Task",
    "inbox.triageAsIdea": "Future Idea",
    "inbox.triageAsNote": "Add Note",
    "inbox.discard": "Discard",
    "inbox.selectBlock": "Select the block for this task:",
    "inbox.cancel": "Cancel",
    "inbox.create": "Create",
    "inbox.creating": "Creating...",
    "inbox.triageAsIdeaSuccess": "Converted to future idea!",
    "inbox.triageAsNoteSuccess": "Converted to note!",
    "inbox.loading": "Loading inbox...",

    // ConfiguracoesPage
    "settings.title": "Settings",
    "settings.subtitle": "Adjust the sanctuary for your needs",
    "settings.error": "Error loading settings",
    "settings.language": "Language / Idioma",
    "settings.languageDesc": "Choose the app display language",
    "settings.focoRitmo": "Focus & Rhythm",
    "settings.focoRitmoDesc": "Adjust how the app understands your work rhythm",
    "settings.limiarHiperfoco": "Hyperfocus Threshold:",
    "settings.limiarDesc": "How much longer than estimated before the app warns you that you are in hyperfocus?",
    "settings.limiarValues": "100% = exactly on time | 150% = 50% more | 300% = 3x the time",
    "settings.horarioFimDia": "End of day time",
    "settings.horarioFimDiaDesc": "When the app stops counting time spent (useful to separate work day)",
    "settings.ia": "Intelligent Assistance",
    "settings.iaDesc": "Features that use AI to help",
    "settings.iaCheckbox": "Activate estimated time suggestions via AI",
    "settings.iaCheckboxDesc": "The app can suggest how long a task should take",
    "settings.camposAvancados": "Advanced Task Fields",
    "settings.camposAvancadosDesc": "Which additional fields appear when creating a task?",
    "settings.energiaEstimada": "Estimated Energy (low/medium/high)",
    "settings.contexto": "Context (e.g. \"need breakfast\", \"quick between meetings\")",
    "settings.prioridade": "Numeric Priority (1-5)",
    "settings.camposDesc": "Disabled fields do not appear when creating tasks, keeping the interface simple",
    "settings.modulosOpcionais": "Optional Modules",
    "settings.modulosOpcionaisDesc": "Features that you can enable or disable",
    "settings.diarioVisual": "Visual Diary (planned for Phase 11)",
    "settings.rastreadorHabitos": "Habits Tracker (planned for Phase 11)",
    "settings.autoSave": "All changes are saved automatically.",
    "settings.saving": "Saving...",
    "settings.pomodoro": "Pomodoro Technique",
    "settings.pomodoroDesc": "Customize your work and break intervals",
    "settings.pomoDuration": "Duration of each work session",
    "settings.pomoDurationDesc": "How long you work in each \"tomato\" (focused session)",
    "settings.pomoShortBreak": "Short break between sessions",
    "settings.pomoShortBreakDesc": "Quick rest time after each work session",
    "settings.pomoLongBreak": "Long break to recharge",
    "settings.pomoLongBreakDesc": "Longer rest after multiple sessions to recover",
    "settings.pomoUntilLongBreak": "Sessions until long break",
    "settings.pomoUntilLongBreakDesc": "How many sessions to complete before taking a long break",
    "task.pomodoroEstimated": "Pomodoros needed",

    // Componentes: TaskCard & TaskModal
    "task.programming": "Programming",
    "task.currentFocus": "Current Focus",
    "task.isProgramming": "Is it a programming task?",
    "task.tip": "Tip: After saving, click \"▼ View checklist\" to add checklist items.",
    "task.edit": "Edit Task",
    "task.create": "Create New Task",
    "task.title": "Title *",
    "task.description": "Description",
    "task.estimatedTime": "Estimated time (minutes)",
    "task.confirmPassword": "Confirm Password",
    "task.save": "Save",
    "task.saving": "Saving...",
    "task.checklist": "Checklist",
    "task.addChecklist": "+ Add item",
    "task.newChecklistItem": "New item...",
    "task.verChecklist": "View checklist",
    "task.ocultarChecklist": "Hide checklist",
    "task.titleRequired": "Task title is required",

    // Componentes: CaptureDesvioModal
    "deviation.captured": "Deviation Captured",
    "deviation.subtitle": "Record this out-of-scope thought and get back to focus.",
    "deviation.placeholder": "What is on your mind right now?",
    "deviation.placeholderText": "E.g. Remembered to answer client's email...",
    "deviation.errorEmpty": "Please describe your thought",
    "deviation.errorCapture": "Error capturing deviation",
    "deviation.tag": "How to categorize this thought?",
    "deviation.tagNone": "No Category",
    "deviation.tagUrgent": "Urgent",
    "deviation.tagIdea": "Spontaneous Idea",
    "deviation.tagUnrelated": "Out of Scope",
    "deviation.save": "Save and Stay Focused",
    "deviation.saving": "Saving...",
    "deviation.back": "Back",

    // Componentes: CaptureThoughtModal
    "thought.capture": "Capture Thought",
    "thought.placeholder": "Write down what crossed your mind...",
    "thought.details": "More Details (Optional)",
    "thought.detailsPlaceholder": "Add context or extra notes...",
    "thought.category": "Initial Category",
    "thought.catIdea": "Idea",
    "thought.catTask": "Task",
    "thought.catNote": "Note",
    "thought.save": "Send to Inbox",
    "thought.saving": "Sending...",

    // Componentes: BlocoModal
    "block.createTitle": "Create New Block",
    "block.editTitle": "Edit Block",
    "block.icon": "Icon",
    "block.name": "Block Name *",
    "block.namePlaceholder": "E.g. University Studies",
    "block.desc": "Description",
    "block.descPlaceholder": "Short description...",
    "block.category": "Category",
    "block.catLearning": "Learning",
    "block.catCareer": "Career",
    "block.catPersonal": "Personal",
    "block.catLeisure": "Leisure",
    "block.metaLabel": "Meta Label",
    "block.metaLabelPlaceholder": "E.g. Chapters",
    "block.metaTotal": "Meta Total",
    "block.save": "Save",
    "block.saving": "Saving...",
    "block.addLink": "Add Link",
    "block.linkTitlePlaceholder": "Link title",
    "block.linkUrlPlaceholder": "https://...",
    "block.linkFieldsRequired": "Fill in the title and the link",
    "block.linkSaveError": "Error saving link",

    // Componentes: IdeiaModal
    "idea.createTitle": "Create New Idea",
    "idea.editTitle": "Edit Idea",
    "idea.titleLabel": "Title *",
    "idea.titlePlaceholder": "Brilliant idea...",
    "idea.desc": "Description",
    "idea.descPlaceholder": "More details...",
    "idea.tag": "Tag",
    "idea.save": "Save",
    "idea.saving": "Saving...",

    // FocusMode
    "focus.active": "Active Focus",
    "focus.completed": "Complete",
    "focus.capture": "Capture Deviation",
    "focus.confirmExit": "Are you sure you want to exit Focus Mode? Active time spent will be lost.",
    "focus.exitWithoutSaving": "Exit (without saving)",
    "focus.estimated": "Estimated",
    "focus.elapsed": "Elapsed",
    "focus.pause": "⏸️ Pause",
    "focus.resume": "▶️ Resume",
    "focus.hyperfocusWarning": "⚡ You exceeded the hyperfocus threshold! Are you okay?",

    // Mensagens de Erro
    "error.savingBloco": "Error saving block",
    "error.savingTask": "Error saving task",

    // Componentes Genéricos (BlocoCard, TaskCard, etc)
    "common.user": "User",
    "common.active": "Active",
    "common.edit": "Edit",
    "common.archive": "Archive",
    "common.confirm": "Confirm",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.save": "Save",
    "common.close": "Close",
    "common.restore": "Restore",
    "common.unmark": "Unmark",
    "common.markComplete": "Mark complete",
    "common.focusMode": "Focus Mode",
    "common.default": "Default",
    "common.custom": "Custom Color",
    "common.done": "Done",

    // ColorWheelPicker
    "color.default": "Default",
    "color.custom": "Custom Color",
    "color.hexCode": "HEX Code",
    "color.done": "Done",

    "dates.title": "Important Dates",
    "dates.add": "Add Date",
    "dates.noDates": "No important dates set for this block.",
    "dates.titleLabel": "Title",
    "dates.descLabel": "Description (optional)",
    "dates.dateLabel": "Date",
    "notifications.title": "Notifications",
    "notifications.empty": "No new notifications.",
    "notifications.markRead": "Mark as read",
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("broto_language");
    return (saved === "pt" || saved === "en" ? saved : "pt") as Language;
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("broto_language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
